name: real_estate
description: A new Flutter project.
publish_to: 'none' 
#################
version: 1.0.0+1
#################
environment:
  sdk: ">=2.16.1 <3.0.0"

#######

dependencies:
  flutter:
    sdk: flutter
  page_indicator: ^0.4.1
  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  footer: ^0.0.4
  http: ^0.13.4
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.5+3
  image_picker_for_web: ^2.1.8
  image_network: ^2.5.1
  toast: ^0.1.5
  
  
 

  syncfusion_flutter_pdfviewer: ^20.2.40-beta
  path_provider: ^2.0.11
  flutter_downloader: ^1.8.1
  permission_handler: ^9.2.0
  
 
  flutter_profile_picture: ^2.0.0
  lottie: ^1.4.2
  animated_text_kit: ^4.2.2
  restart_app: 
  

 

 
  

#######
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
#######
flutter:
  uses-material-design: true
  assets:
    - images/im.png
    - images/imb.png
    - images/st.png
    - images/im2.jfif 
    - images/im3.jfif
    - images/im4.jfif  
    - images/im5.jfif  
    - images/im6.jfif
    - images/im7.jfif  
    - images/im8.jfif
    - images/logo.jpg  
    - images/s.jpg
    - lotties/1.json
    - lotties/2.json
    - lotties/3.json  
    - lotties/4.json
    - lotties/5.json
    - lotties/6.json
    - lotties/7.json
    - lotties/8.json
    - lotties/9.json
    


    
##########
  
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
